modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="bareessentials" #mandatory
version="0.1" #mandatory
displayName="Bare Essentials" #mandatory
authors="Val and Coffee" #optional
description='''
Features:
* New Rocks that drop ore chunks and valuable gemstones
* New Gemstones and Gemstone Blocks
* 17 different Wax Blocks that can melt when heat sources are placed next to them
* Wax Flakes! Delicious!
* A Stone Knife
* Fossils
* And an Outback biome
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
